import type {Data,Person,PersonnelEvent} from './personnel';
import {workload,DEFAULT_WORK_SETTINGS} from './workload';
export type ActivityParticipant={personId:string;function:string;name?:string};
export type Activity={id:string;name:string;start:string;end:string;coordinatorId:string;coordinatorName?:string;participants:ActivityParticipant[]};
export function validateActivity(input:any):Activity{const text=(v:any,n:number)=>typeof v==='string'?v.trim().slice(0,n):'',id=text(input?.id,80),name=text(input?.name,500),coordinatorId=text(input?.coordinatorId,80),start=new Date(input?.start),end=new Date(input?.end);if(!/^[a-zA-Z0-9-]{8,80}$/.test(id)||!name||!Number.isFinite(start.getTime())||!Number.isFinite(end.getTime())||end<=start)throw Error('Completa la labor y las fechas/horas; la finalización debe ser posterior al inicio.');if(!Array.isArray(input.participants)||!input.participants.length||input.participants.length>200)throw Error('Selecciona entre uno y 200 asistentes.');const participants:ActivityParticipant[]=input.participants.map((p:any)=>({personId:text(p?.personId,80),function:text(p?.function,150)}));if(participants.some(p=>!p.personId)||new Set(participants.map(p=>p.personId)).size!==participants.length)throw Error('Revisa los asistentes; no pueden repetirse.');if(!participants.some(p=>p.personId===coordinatorId))throw Error('Selecciona al encargado entre los asistentes.');return{id,name,start:start.toISOString(),end:end.toISOString(),coordinatorId,participants};}
export function activityAvailability(person:Person,data:Data,start:string,end:string,activityId=''){
 const from=Date.parse(start),to=Date.parse(end);if(!Number.isFinite(from)||!Number.isFinite(to)||to<=from)return{available:false,reason:'Completa el horario'};
 const events=data.events.filter(e=>e.activityId!==activityId||!activityId);
 const conflict=events.find(e=>e.personId===person.id&&Date.parse(e.start)<to&&Date.parse(e.end)>from);if(conflict)return{available:false,reason:'Cruce con '+(conflict.activityId?'otra actividad':conflict.kind.toLowerCase())};
 const w=workload(person,events,data.workSettings||DEFAULT_WORK_SETTINGS,from);return{available:w.canAssign,reason:w.canAssign?'Disponible para este horario':w.status!=='Disponible'?w.status:w.alert};
}
export function activityEvents(a:Activity):PersonnelEvent[]{return a.participants.map(p=>({id:'activity-'+a.id+'-'+p.personId,personId:p.personId,kind:'Servicio',start:a.start,end:a.end,place:a.name,notes:p.function,activityId:a.id}));}
const parts=(value:string)=>new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Bogota',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(value)).split(' ');
export function activityLocal(value:string){const [date,time]=parts(value);return{date,time};}
export function activityMessage(a:Activity,people:Person[]=[]){const person=(id:string,fallback?:string)=>people.find(p=>p.id===id)?.name||fallback||'Funcionario',from=activityLocal(a.start),to=activityLocal(a.end),day=(date:string)=>date.split('-').reverse().join('/');return ['ACTIVIDAD / LABOR',a.name,'','Fecha desde: '+day(from.date),'Fecha hasta: '+day(to.date),'Horario desde: '+from.time,'Horario hasta: '+to.time,'Hora de Colombia','','Encargado: '+person(a.coordinatorId,a.coordinatorName),'','ASISTENTES',...a.participants.map((p,i)=>`${i+1}. ${person(p.personId,p.name)}${p.function?' — Función: '+p.function:''}`)].join('\n');}
