import {workload,DEFAULT_WORK_SETTINGS,validateWorkSettings,type WorkSettings} from './workload';
import {validateQualifications,bogotaDate,validDate,addDays,type Qualification,type TrainingRequirement} from './qualifications';
export {bogotaDate,validDate,addDays} from './qualifications';
export type Person={id:string;document:string;name:string;company?:string;firstName?:string;secondName?:string;firstSurname?:string;secondSurname?:string;role:string;phone:string;status:string;notes:string;titles?:string;strengths?:string;accessRole?:string;invitationRole?:string;qualifications?:Qualification[]|string;contractEnd?:string;contractIndefinite?:boolean|number};
export type PersonnelEvent={id:string;personId:string;kind:string;start:string;end:string;place:string;notes:string;authorizedBy?:string;extraDays?:number};
export type Discipline={id:string;personId:string;kind:string;reason:string;start:string;end:string;notes:string};
export type Meal={id:string;personId:string;date:string;breakfast:number;lunch:number;dinner:number};
export type Data={people:Person[];events:PersonnelEvent[];discipline?:Discipline[];meals?:Meal[];trainingRequirements?:TrainingRequirement[];workSettings?:WorkSettings};
export const companies=['SK','E-SECURITY'];
export const roles=['Director de seguridad','Jefe de seguridad','Supervisor','Escolta','Operador de seguridad','SST'];
export const statuses=['Disponible','De permiso','De vacaciones','En descanso','No disponible','Inactivo'];
const text=(v:unknown,max=500)=>typeof v==='string'?v.trim().slice(0,max):'';
export const listItems=(v:unknown):string[]=>Array.isArray(v)?v.map(x=>text(x,150)).filter(Boolean):typeof v==='string'?v.split('\n').map(x=>x.trim()).filter(Boolean):[];
export function permissionDays(start:string,end:string){return Math.ceil((Date.parse(end)-Date.parse(start))/86400000)}
export function mealBlocked(person:Person,events:PersonnelEvent[],date:string){if(['Inactivo','De permiso','De vacaciones'].includes(person.status))return true;const start=date+'T05:00:00.000Z',end=addDays(date,1)+'T05:00:00.000Z';return events.some(e=>e.personId===person.id&&['Permiso','Vacaciones'].includes(e.kind)&&e.start<end&&e.end>start)}
export function validateRecord(type:unknown,input:any):any{
 if(!input||typeof input!=='object')throw Error('Registro inválido.');const id=text(input.id,80);if(!/^[a-zA-Z0-9-]{8,80}$/.test(id))throw Error('Identificador inválido.');
 if(type==='settings')return validateWorkSettings(input);
 if(type==='course'){const name=text(input.name,150),validityMonths=Number(input.validityMonths);if(!name||!Number.isInteger(validityMonths)||validityMonths<0||validityMonths>120||id.startsWith('license-'))throw Error('Completa capacitación y vigencia válida (0 a 120 meses).');return{id,name,validityMonths}}
 if(type==='person'){const document=text(input.document,40),firstName=text(input.firstName,60),secondName=text(input.secondName,60),firstSurname=text(input.firstSurname,60),secondSurname=text(input.secondSurname,60),company=text(input.company,30),role=text(input.role,80),status=text(input.status,40)==='Descanso'?'En descanso':text(input.status,40);if(!document||!firstName||!firstSurname)throw Error('Completa documento, primer nombre y primer apellido.');if(!companies.includes(company))throw Error('Selecciona SK o E-SECURITY.');if(!roles.includes(role)||!statuses.includes(status))throw Error('Selecciona cargo y disponibilidad válidos.');const titles=listItems(input.titles),strengths=listItems(input.strengths);if(titles.length>50||strengths.length>50)throw Error('Máximo 50 títulos o fortalezas.');const qualifications=input.qualifications===undefined?undefined:validateQualifications(input.qualifications),contractEnd=input.contractEnd===undefined?undefined:text(input.contractEnd,10),contractIndefinite=input.contractIndefinite===undefined?undefined:!!input.contractIndefinite;if(contractEnd&&!validDate(contractEnd))throw Error('Revisa la fecha de vencimiento del contrato.');return{qualifications,contractEnd,contractIndefinite,id,document,name:[firstName,secondName,firstSurname,secondSurname].filter(Boolean).join(' '),firstName,secondName,firstSurname,secondSurname,company,role,status,phone:text(input.phone,40),notes:text(input.notes),titles:titles.join('\n'),strengths:strengths.join('\n')}}
 if(type==='event'){const start=new Date(input.start),end=new Date(input.end),personId=text(input.personId,80),kind=text(input.kind,30);if(!personId||!['Servicio','Permiso','Vacaciones'].includes(kind)||!Number.isFinite(start.getTime())||!Number.isFinite(end.getTime())||end<=start)throw Error('La finalización debe ser posterior al inicio.');const place=text(input.place,150);if(!place)throw Error('Ingresa el lugar o motivo.');const extraDays=kind==='Permiso'?Math.max(0,permissionDays(start.toISOString(),end.toISOString())-10):0,authorizedBy=text(input.authorizedBy,150);if(extraDays&&!authorizedBy)throw Error('Indica quién autorizó los días adicionales del permiso.');return{id,personId,kind,start:start.toISOString(),end:end.toISOString(),place,notes:text(input.notes),authorizedBy,extraDays}}
 if(type==='discipline'){const personId=text(input.personId,80),kind=text(input.kind,40),reason=text(input.reason,1000),start=text(input.start,10),end=text(input.end,10);if(!personId||!['Sanción','Llamado de atención'].includes(kind)||!reason||!validDate(start)||!validDate(end)||end<start)throw Error('Completa funcionario, motivo y fechas válidas.');return{id,personId,kind,reason,start,end,notes:text(input.notes)}}
 throw Error('Tipo de registro inválido.');
}
export function personStatus(person:Person,events:PersonnelEvent[],now=Date.now(),settings:WorkSettings=DEFAULT_WORK_SETTINGS){return workload(person,events,settings,now).status}
export function hours(event:PersonnelEvent){return Math.max(0,(Date.parse(event.end)-Date.parse(event.start))/3600000)}
export function monthHours(personId:string,events:PersonnelEvent[],month:string){const start=Date.parse(month+'-01T00:00:00-05:00'),[y,m]=month.split('-').map(Number),end=Date.parse(`${m===12?y+1:y}-${String(m===12?1:m+1).padStart(2,'0')}-01T00:00:00-05:00`);return events.filter(e=>e.personId===personId&&e.kind==='Servicio').reduce((sum,e)=>sum+Math.max(0,(Math.min(Date.parse(e.end),end,Date.now())-Math.max(Date.parse(e.start),start))/3600000),0)}
export const dateTime=(iso:string)=>new Date(iso).toLocaleString('es-CO',{timeZone:'America/Bogota',day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'});
export const currentMonth=()=>bogotaDate().slice(0,7);
