import {DEFAULT_WORK_SETTINGS} from './workload';
import{env}from'cloudflare:workers';
import{validateRecord}from'./personnel';
export const cors={'Access-Control-Allow-Origin':'https://controlesmineras.github.io','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type,Authorization','Vary':'Origin'};
export const response=(body:unknown,status=200)=>Response.json(body,{status,headers:{'Cache-Control':'no-store',...cors}});
export const db=()=>{if(!env.DB)throw Error('Almacenamiento no disponible.');return env.DB};
export const personColumns='id,document,name,company,first_name AS firstName,second_name AS secondName,first_surname AS firstSurname,second_surname AS secondSurname,role,phone,status,notes,titles,strengths,qualifications_json AS qualifications,contract_end AS contractEnd,contract_indefinite AS contractIndefinite';
export const eventColumns='id,person_id AS personId,kind,start,end,place,notes,authorized_by AS authorizedBy,extra_days AS extraDays';
export const hash=async(value:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value))),x=>x.toString(16).padStart(2,'0')).join('');
export function same(a:string,b:string){if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0}
export function originAllowed(req:Request){const origin=req.headers.get('Origin');return !origin||origin===cors['Access-Control-Allow-Origin']||origin===new URL(req.url).origin}
export async function passwordHash(password:string,salt:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:new TextEncoder().encode(salt),iterations:100000},key,256);return Array.from(new Uint8Array(bits),x=>x.toString(16).padStart(2,'0')).join('')}
export async function admin(req:Request){if(!originAllowed(req))return false;const token=req.headers.get('Authorization')?.replace(/^Bearer /,'')||'';if(!token)return false;const configured=await db().prepare('SELECT username,version FROM admin_credentials WHERE username=?').bind('admin').first<any>();if(!configured){const expected=(env as any).GP_ACCESS_HASH;if(!!expected&&same(await hash(token),expected))return true;const person=await employee(req);return person?.accessRole==='Administrador'}try{const parts=token.split('.');if(parts.length!==2||!same(await signature(parts[0]),parts[1]))return false;const payload=JSON.parse(atob(parts[0]));if(payload.kind==='admin')return payload.username==='admin'&&payload.version===configured.version&&payload.exp>Date.now();const person=await employee(req);return person?.accessRole==='Administrador'}catch{return false}}
export async function adminSession(version:string){const payload=btoa(JSON.stringify({kind:'admin',username:'admin',version,exp:Date.now()+86400000}));return payload+'.'+await signature(payload)}
export async function setupAllowed(token:string){return !!(env as any).GP_ADMIN_SETUP_HASH&&same(await hash(token),(env as any).GP_ADMIN_SETUP_HASH)}

async function signature(payload:string){if(!(env as any).GP_ACCESS_HASH)throw Error('Acceso no configurado.');const key=await crypto.subtle.importKey('raw',new TextEncoder().encode((env as any).GP_ACCESS_HASH),{name:'HMAC',hash:'SHA-256'},false,['sign']);return Array.from(new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(payload))),x=>x.toString(16).padStart(2,'0')).join('')}
export async function sessionToken(id:string,version:string){const payload=btoa(JSON.stringify({id,version,exp:Date.now()+86400000}));return payload+'.'+await signature(payload)}
export async function employee(req:Request){if(!originAllowed(req))return null;try{const raw=req.headers.get('Authorization')?.replace(/^Bearer /,'')||'',parts=raw.split('.');if(parts.length!==2||!same(await signature(parts[0]),parts[1]))return null;const p=JSON.parse(atob(parts[0]));if(p.exp<=Date.now())return null;return await db().prepare('SELECT p.id,p.document,p.name,p.status,p.company,p.role,p.phone,p.notes,p.titles,p.strengths,p.qualifications_json AS qualifications,p.contract_end AS contractEnd,p.contract_indefinite AS contractIndefinite,c.access_role AS accessRole FROM people p JOIN employee_credentials c ON p.id=c.person_id WHERE p.id=? AND c.version=? AND p.status<>?').bind(p.id,p.version,'Inactivo').first<any>();}catch{return null}}
export async function saveEvent(input:any,owner?:string){const r=validateRecord('event',input);if(owner&&(r.personId!==owner||r.kind!=='Permiso'))throw Error('Solo puedes reportar tus propios permisos.');const person=await db().prepare('SELECT id,status FROM people WHERE id=?').bind(r.personId).first();if(!person||person.status==='Inactivo')throw Error('El funcionario no está disponible.');const existing=await db().prepare('SELECT person_id FROM events WHERE id=?').bind(r.id).first<any>();if(owner&&existing&&existing.person_id!==owner)throw Error('Registro no autorizado.');
const result=await db().prepare(`INSERT INTO events (id,person_id,kind,start,end,place,notes,authorized_by,extra_days,updated_at) SELECT ?,?,?,?,?,?,?,?,?,? WHERE NOT EXISTS (SELECT 1 FROM events WHERE person_id=? AND id<>? AND start<? AND end>?) ON CONFLICT(id) DO UPDATE SET person_id=excluded.person_id,kind=excluded.kind,start=excluded.start,end=excluded.end,place=excluded.place,notes=excluded.notes,authorized_by=excluded.authorized_by,extra_days=excluded.extra_days,updated_at=excluded.updated_at`).bind(r.id,r.personId,r.kind,r.start,r.end,r.place,r.notes,r.authorizedBy,r.extraDays,new Date().toISOString(),r.personId,r.id,r.end,r.start).run();if(!result.meta.changes)throw Error('El horario se cruza con otro servicio, permiso o vacaciones.');return r;}

export async function getWorkSettings(){return await db().prepare('SELECT id,min_rest_hours AS minRestHours,max_work_hours_24 AS maxWorkHours24 FROM work_settings WHERE id=?').bind('workload-settings').first<any>()||DEFAULT_WORK_SETTINGS}
