import type {Person,Data} from './personnel';
export const bogotaDate=(now=new Date())=>new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Bogota'}).format(now);
export function addDays(date:string,days:number){return new Date(Date.parse(date+'T12:00:00Z')+days*86400000).toISOString().slice(0,10)}
export function validDate(d:unknown):d is string{return typeof d==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(d)&&Number.isFinite(Date.parse(d+'T12:00:00Z'))&&new Date(d+'T12:00:00Z').toISOString().slice(0,10)===d}

export type Qualification={id:string;requirementId:string;name:string;issuedOn:string;expiresOn:string;noExpiry:boolean;category:string};
export type TrainingRequirement={id:string;name:string;validityMonths:number};
export const LICENSES:TrainingRequirement[]=[{id:'license-car',name:'Licencia de conducción · Carro',validityMonths:0},{id:'license-motorcycle',name:'Licencia de conducción · Moto',validityMonths:0}];
export function qualificationItems(value:unknown):Qualification[]{try{const rows=typeof value==='string'?JSON.parse(value):value;return Array.isArray(rows)?rows:[];}catch{return [];}}
export function personQualifications(p:Person){const rows=qualificationItems(p.qualifications);return [...rows,...(p.titles||'').split('\n').map(n=>n.trim()).filter(Boolean).filter(name=>!rows.some(r=>r.name===name)).map((name,i)=>({id:'legacy-title-'+i,requirementId:'',name,issuedOn:'',expiresOn:'',noExpiry:true,category:''}))];}
export function requirements(data:Data,person?:Pick<Person,'role'>){return [...(person?.role==='Preparación de alimentos'?[]:LICENSES),...(data.trainingRequirements||[])];}
export function addMonths(date:string,months:number){if(!validDate(date))return '';const [y,m,d]=date.split('-').map(Number),target=new Date(Date.UTC(y,m-1+months,1)),last=new Date(Date.UTC(target.getUTCFullYear(),target.getUTCMonth()+1,0)).getUTCDate();return `${target.getUTCFullYear()}-${String(target.getUTCMonth()+1).padStart(2,'0')}-${String(Math.min(d,last)).padStart(2,'0')}`;}
export function expiryStatus(expiresOn:string,noExpiry=false,today=bogotaDate()){if(noExpiry)return 'Vigente';if(!validDate(expiresOn))return 'Pendiente';return expiresOn<today?'Vencida':expiresOn<=addDays(today,30)?'Próxima a vencer':'Vigente';}
export function requirementStatus(p:Person,r:TrainingRequirement,today=bogotaDate()){
 const rows=qualificationItems(p.qualifications).filter(q=>q.requirementId===r.id),eligible=rows.filter(q=>!q.issuedOn||q.issuedOn<=today);
 const ranked=eligible.map(q=>({record:q,status:expiryStatus(q.expiresOn,q.noExpiry&&!r.id.startsWith('license-')&&r.validityMonths===0,today)})).sort((a,b)=>['Vigente','Próxima a vencer','Vencida','Pendiente'].indexOf(a.status)-['Vigente','Próxima a vencer','Vencida','Pendiente'].indexOf(b.status)||b.record.expiresOn.localeCompare(a.record.expiresOn));
 return ranked[0]||{record:rows[0],status:'Pendiente'};
}
export function validateQualifications(value:unknown):Qualification[]{if(typeof value==='string'){try{value=JSON.parse(value)}catch{throw Error('Capacitaciones inválidas.')}}const rows=qualificationItems(value);if(!Array.isArray(value)&&typeof value!=='string')throw Error('Capacitaciones inválidas.');if(rows.length>100)throw Error('Máximo 100 títulos o capacitaciones.');const result=rows.map((r:any)=>{const s=(v:any,n=150)=>typeof v==='string'?v.trim().slice(0,n):'';const id=s(r.id,80),name=s(r.name),requirementId=s(r.requirementId,80),issuedOn=s(r.issuedOn,10),expiresOn=s(r.expiresOn,10),noExpiry=!!r.noExpiry;if(!/^[a-zA-Z0-9-]{8,80}$/.test(id)||!name)throw Error('Completa el nombre del título o capacitación.');if((issuedOn&&!validDate(issuedOn))||(expiresOn&&!validDate(expiresOn))||(issuedOn&&expiresOn&&expiresOn<issuedOn))throw Error('Revisa las fechas de la capacitación.');if(requirementId.startsWith('license-')&&(!LICENSES.some(l=>l.id===requirementId)||noExpiry))throw Error('La licencia requiere una fecha de vencimiento.');return{id,name,requirementId,issuedOn,expiresOn,noExpiry,category:s(r.category,40)};});if(new Set(result.map(r=>r.id)).size!==result.length)throw Error('Capacitación duplicada.');return result;}
