'use client';
import {useState} from 'react';
import {type Data,dateTime} from '@/lib/personnel';
const labels:Record<string,string>={document:'Documento',name:'Nombre completo',company:'Empresa',firstName:'Primer nombre',secondName:'Segundo nombre',firstSurname:'Primer apellido',secondSurname:'Segundo apellido',role:'Cargo',phone:'Teléfono',status:'Disponibilidad',notes:'Observaciones',titles:'Títulos',strengths:'Fortalezas',qualifications:'Títulos, capacitaciones y licencias',contractEnd:'Vencimiento del contrato',contractIndefinite:'Contrato sin vencimiento',personId:'Funcionario',kind:'Tipo de registro',reason:'Motivo',start:'Desde',end:'Hasta',place:'Puesto / motivo',authorizedBy:'Autorizado por',extraDays:'Días adicionales',validityMonths:'Vigencia en meses',minRestHours:'Descanso mínimo (horas)',maxWorkHours24:'Alerta de carga en 24 h (horas)',accessRole:'Tipo de acceso',expiresAt:'Vencimiento del enlace'};
const types:Record<string,string>={person:'Ficha',event:'Servicio / ausencia',discipline:'Llamado / sanción',course:'Capacitación obligatoria',settings:'Carga y descanso',access:'Acceso'};
export default function AuditPanel({data}:{data:Data}){
 const[person,setPerson]=useState(''),[actor,setActor]=useState('');const logs=data.auditLogs||[],actors=Array.from(new Map(logs.map(l=>[l.actorId,l.actorName])).entries());
 const value=(field:string,v:any):string=>field==='personId'?data.people.find(p=>p.id===v)?.name||v||'Sin registro':typeof v==='boolean'?v?'Sí':'No':Array.isArray(v)?v.map(q=>[q.name,q.category,q.issuedOn?'Obtención: '+q.issuedOn:'',q.expiresOn?'Vence: '+q.expiresOn:'',q.noExpiry?'Sin vencimiento':''].filter(Boolean).join(' · ')).join('\n')||'Sin registro':v===''||v==null?'Sin registro':field==='expiresAt'?dateTime(new Date(v).toISOString()):String(v);
 const rows=logs.filter(l=>(!person||l.personId===person)&&(!actor||l.actorId===actor));
 return <div className="audit-panel"><p>Los cambios de administración se registran desde la incorporación de este historial. Se muestran los 500 más recientes.</p><div className="training-filters"><label>Funcionario<select value={person} onChange={e=>setPerson(e.target.value)}><option value="">Todos</option>{data.people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Administrador<select value={actor} onChange={e=>setActor(e.target.value)}><option value="">Todos</option>{actors.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label></div><div className="history">{rows.map(l=><article key={l.id}><strong>{l.action} · {types[l.entityType]||l.entityType}</strong><span>{dateTime(l.occurredAt)} · Administrador: {l.actorName}{l.actorDocument?' · '+l.actorDocument:''}</span>{l.personId&&<span>Funcionario: {data.people.find(p=>p.id===l.personId)?.name||l.personId}</span>}<details><summary>Ver cambios</summary><div className="table-wrap"><table className="gp-table"><thead><tr><th>Campo</th><th>Antes</th><th>Después</th></tr></thead><tbody>{(JSON.parse(l.changes) as any[]).map(c=><tr key={c.field}><td>{labels[c.field]||c.field}</td><td className="audit-value">{value(c.field,c.before)}</td><td className="audit-value">{value(c.field,c.after)}</td></tr>)}</tbody></table></div></details></article>)}{!rows.length&&<p className="empty">Sin cambios registrados para estos filtros.</p>}</div></div>;
}
