'use client';
import{useEffect,useState}from'react';import{ShieldCheck,LogOut,CalendarDays,Utensils}from'lucide-react';import{bogotaDate,addDays,validDate,type PersonnelEvent}from'@/lib/personnel';
const API='https://gestion-de-personal.nelsoncaste86.chatgpt.site/api/self',KEY='gestion-personal-self-session';
export default function Employee({onAdmin}:{onAdmin:()=>void}){
 const[token,setToken]=useState(''),[document,setDocument]=useState(''),[code,setCode]=useState(''),[info,setInfo]=useState<any>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[meals,setMeals]=useState({breakfast:false,lunch:false,dinner:false}),[start,setStart]=useState(bogotaDate()),[end,setEnd]=useState(addDays(bogotaDate(),9)),[reason,setReason]=useState(''),[authorizedBy,setAuthorizedBy]=useState('');
 const days=validDate(start)&&validDate(end)&&end>=start?(Date.parse(end+'T12:00:00Z')-Date.parse(start+'T12:00:00Z'))/86400000+1:0,extra=Math.max(0,days-10);
 async function request(input?:any,session=token){const r=await fetch(API,{method:input?'POST':'GET',cache:'no-store',headers:{'Content-Type':'application/json',...(session?{Authorization:'Bearer '+session}:{})},...(input?{body:JSON.stringify(input)}:{})});const j:any=await r.json();if(!r.ok){if(r.status===401&&input?.action!=='login'){localStorage.removeItem(KEY);setToken('');setInfo(null);}throw Error(j.error||'No se pudo completar el reporte.');}return j;}
 async function load(session=token){try{const j=await request(undefined,session);setInfo(j);setMeals({breakfast:!!j.meal?.breakfast,lunch:!!j.meal?.lunch,dinner:!!j.meal?.dinner});}catch(e){setError((e as Error).message)}}
 useEffect(()=>{const saved=localStorage.getItem(KEY)||'';if(saved){setToken(saved);void load(saved);}},[]);
 useEffect(()=>{if(!token)return;const t=setInterval(()=>{if(info?.date!==addDays(bogotaDate(),1)){setMessage('Comenzó un nuevo día. Reporta los alimentos de mañana.');void load();}},30000);return()=>clearInterval(t)},[token,info?.date]);
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const j=await request({action:'login',document,code},'');localStorage.setItem(KEY,j.token);setToken(j.token);setCode('');await load(j.token);}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function save(input:any){setBusy(true);setError('');setMessage('');try{await request(input);setMessage(input.action==='meals'?'Alimentos reportados. Puedes cambiarlos hasta las 11:59 p. m. de hoy.':'Salida de permiso reportada.');if(input.action==='permission'){setReason('');setAuthorizedBy('');}await load();}catch(e){setError((e as Error).message);await load();}finally{setBusy(false)}}
 if(!token||!info)return <div className="access-page"><div className="access-card"><ShieldCheck size={40}/><h1>GESTIÓN DE PERSONAL</h1><p>Ingresa para reportar tus permisos y los alimentos de mañana.</p><form onSubmit={login}><label>Número de documento<input required value={document} onChange={e=>setDocument(e.target.value)} autoComplete="username"/></label><label>Clave personal<input required type="password" value={code} onChange={e=>setCode(e.target.value)} autoComplete="current-password"/></label><button className="primary" disabled={busy}>{busy?'Ingresando…':'Ingresar'}</button></form>{error&&<p className="notice" role="alert">{error}</p>}<small>Solicita tu clave personal al administrador.</small><button className="secondary portal-admin" onClick={onAdmin}>Administración</button></div></div>;
 return <div className="app"><header className="top"><div className="brand"><ShieldCheck/><div><h1>GESTIÓN DE PERSONAL</h1><span>{info.person.name} · {info.person.document}</span></div></div><button className="secondary" onClick={()=>{localStorage.removeItem(KEY);setToken('');setInfo(null);setMessage('');setError('')}}><LogOut size={16}/>Salir</button></header><main>{error&&<p className="notice" role="alert">{error}</p>}{message&&<p className="success-notice" role="status">{message}</p>}<div className="employee-grid"><section className="employee-card"><h2><Utensils/>Alimentos de mañana</h2><p className="meal-date">{info.date.split('-').reverse().join('/')}</p><p>Plazo: hoy hasta las 11:59 p. m. · Hora de Colombia.</p>{info.blocked?<p className="notice">No puedes consumir alimentos durante permisos o vacaciones. El reporte está bloqueado para esta fecha.</p>:<form onSubmit={e=>{e.preventDefault();void save({action:'meals',date:info.date,...meals})}}>{[['breakfast','Desayuno'],['lunch','Almuerzo'],['dinner','Cena']].map(([key,label])=><label className="meal-check" key={key}><input type="checkbox" checked={meals[key as keyof typeof meals]} onChange={e=>setMeals({...meals,[key]:e.target.checked})}/>{label}</label>)}<button className="primary" disabled={busy}>{busy?'Guardando…':'Guardar alimentos'}</button></form>}</section><section className="employee-card"><h2><CalendarDays/>Reportar salida de permiso</h2><form onSubmit={e=>{e.preventDefault();void save({action:'permission',record:{id:crypto.randomUUID(),start:start+'T00:00:00-05:00',end:addDays(end,1)+'T00:00:00-05:00',place:reason,authorizedBy,notes:''}})}}><label>Desde<input type="date" required value={start} onChange={e=>setStart(e.target.value)}/></label><label>Hasta (incluido)<input type="date" required min={start} value={end} onChange={e=>setEnd(e.target.value)}/></label><label>Motivo<input required maxLength={150} value={reason} onChange={e=>setReason(e.target.value)}/></label><p>{days} días de permiso · 10 días autorizados{extra>0?' · '+extra+' días adicionales':''}</p>{extra>0&&<label>Adicionales autorizados por<input required maxLength={150} value={authorizedBy} onChange={e=>setAuthorizedBy(e.target.value)}/></label>}<button className="primary" disabled={busy||days<=0}>{busy?'Guardando…':'Reportar permiso'}</button></form></section></div><section className="employee-card"><h2>Mis permisos y vacaciones</h2><div className="history">{info.events.filter((e:PersonnelEvent)=>e.kind!=='Servicio').map((e:PersonnelEvent)=><article key={e.id}><b>{e.kind} · {e.place}</b><span>Desde {bogotaDate(new Date(e.start))} hasta {bogotaDate(new Date(Date.parse(e.end)-1))}</span>{!!e.extraDays&&<small>{e.extraDays} días adicionales · Autorizados por {e.authorizedBy}</small>}</article>)}{!info.events.some((e:PersonnelEvent)=>e.kind!=='Servicio')&&<p>Sin permisos ni vacaciones registrados.</p>}</div></section></main></div>;
}
