'use client';
import {useEffect,useState} from 'react';
import {ShieldCheck,LogOut} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {addDays,bogotaDate,dateTime} from '@/lib/personnel';
const API='https://gestion-de-personal.nelsoncaste86.chatgpt.site/api/kitchen';
const MEALS=[['breakfast','DESAYUNO'],['lunch','ALMUERZO'],['dinner','COMIDA']];
export function KitchenPortal({token,onLogout}:{token:string;onLogout:()=>void}){return <div className="app"><header className="top"><div className="brand"><ShieldCheck/><div><h1>GESTIÓN DE PERSONAL</h1><span>COCINA</span></div></div><button className="secondary" onClick={onLogout}><LogOut size={16}/>Salir</button></header><main><KitchenPanel token={token}/></main></div>}
export default function KitchenPanel({token}:{token:string}){
 const[date,setDate]=useState(addDays(bogotaDate(),1)),[result,setResult]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState('');
 useEffect(()=>{let cancelled=false;async function load(){const next=addDays(bogotaDate(),1);if(next!==date){setDate(next);setSelected('');return;}setBusy(true);try{const r=await fetch(API+'?date='+date,{cache:'no-store',signal:AbortSignal.timeout(15000),headers:{Authorization:'Bearer '+token}}),j:any=await r.json();if(!r.ok)throw Error(j.error||'No se pudo cargar la preparación.');if(!cancelled){setResult(j);setError('');}}catch(e){if(!cancelled){setError((e as Error).message);setResult(null);setSelected('');}}finally{if(!cancelled)setBusy(false)}}setResult(null);void load();const timer=setInterval(()=>void load(),60000);return()=>{cancelled=true;clearInterval(timer)}},[date,token]);
 const names=(result?.rows||[]).filter((p:any)=>!!p[selected]);
 return <section className="employee-card"><h2>Alimentos para mañana</h2><p className="meal-date">{date.split('-').reverse().join('/')}</p><p>Los reportes pueden cambiar hasta las 11:59 p. m. de hoy. Actualización automática cada minuto.</p>{error&&<p className="notice" role="alert">{error}</p>}{busy&&!result&&<p>Cargando reportes…</p>}<div className="meal-totals kitchen-totals">{MEALS.map(([key,label])=><button className="kitchen-meal" key={key} disabled={!result} onClick={()=>setSelected(key)} aria-label={label+': '+(result?result.rows.filter((p:any)=>!!p[key]).length:'cargando')+' · Ver nombres'}><span>{label}</span><b>{result?result.rows.filter((p:any)=>!!p[key]).length:'—'}</b><small>Por preparar</small></button>)}</div>{result&&<small>Actualizado: {dateTime(result.updatedAt)}</small>}<Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected('')}}><DialogContent><DialogTitle>{MEALS.find(([key])=>key===selected)?.[1]}</DialogTitle><DialogDescription>{date.split('-').reverse().join('/')}</DialogDescription>{names.length?<ul className="kitchen-names">{names.map((p:any)=><li key={p.id}>{p.name}</li>)}</ul>:<p>No hay solicitudes para este alimento.</p>}</DialogContent></Dialog></section>;
}
