const fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript'),assert=require('node:assert/strict');const{DatabaseSync}=require('node:sqlite');
let clock=Date.parse('2026-10-04T23:59:59-05:00');class TestDate extends Date{constructor(...a){super(...(a.length?a:[clock]));}static now(){return clock;}}
const sql=new DatabaseSync(':memory:');const migrated=fs.readdirSync('drizzle').filter(x=>x.endsWith('.sql')).sort();for(const file of migrated.slice(0,2))sql.exec(fs.readFileSync('drizzle/'+file,'utf8'));sql.exec("INSERT INTO people (id,document,name,role,status,phone,notes,updated_at,titles,strengths) VALUES ('legacy-person','123','Nombre Antiguo','Escolta','Disponible','','','now','Bachiller','Trabajo en equipo')");for(const file of migrated.slice(2))sql.exec(fs.readFileSync('drizzle/'+file,'utf8'));assert.equal(sql.prepare("SELECT name FROM people WHERE id='legacy-person'").get().name,'Nombre Antiguo');assert.equal(sql.prepare("SELECT titles FROM people WHERE id='legacy-person'").get().titles,'Bachiller');
const DB={prepare(query){let values=[];return{bind(...args){values=args;return this;},async first(){return sql.prepare(query).get(...values)||null},async all(){return{results:sql.prepare(query).all(...values)}},async run(){const r=sql.prepare(query).run(...values);return{meta:{changes:Number(r.changes)}}}}}};
DB.batch=async statements=>{sql.exec('BEGIN');try{const result=[];for(const statement of statements)result.push(await statement.run());sql.exec('COMMIT');return result;}catch(e){sql.exec('ROLLBACK');throw e;}};
const env={DB,GP_ACCESS_HASH:''},cache={};function load(path){if(cache[path])return cache[path];const module={exports:{}};const ctx={module,exports:module.exports,require:id=>{if(id==='cloudflare:workers')return{env};if(id==='@/lib/personnel'||id==='./personnel')return load('lib/personnel.ts');if(id==='@/lib/personnel-server')return load('lib/personnel-server.ts');throw Error(id)},crypto:globalThis.crypto,Date:TestDate,TextEncoder,Uint8Array,Request,Response,URL,btoa,atob,console,Intl};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,ctx);return cache[path]=module.exports;}
const rules=load('lib/personnel.ts'),server=load('lib/personnel-server.ts'),admin=load('app/api/data/route.ts'),self=load('app/api/self/route.ts');
const req=(body,token='admin-secret')=>new Request('https://backend.test/api/data',{method:body?'POST':'GET',headers:{Origin:'https://controlesmineras.github.io',Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
async function call(route,body,token){const response=await route[body?'POST':'GET'](req(body,token));return{status:response.status,data:await response.json()};}
(async()=>{env.GP_ACCESS_HASH=await server.hash('admin-secret');
const person={id:'person-one-123',document:'101',firstName:'Ana',secondName:'María',firstSurname:'Del Río',secondSurname:'López',company:'SK',role:'Directora',status:'Disponible',titles:['Bachiller','Técnica'],strengths:['Trabajo en equipo','Disciplina']};assert.throws(()=>rules.validateRecord('person',person));person.role='Director de seguridad';const p=rules.validateRecord('person',person);assert.equal(p.name,'Ana María Del Río López');assert.equal(p.titles,'Bachiller\nTécnica');assert.throws(()=>rules.validateRecord('person',{...person,company:'Otra'}));assert.equal((await call(admin,{type:'person',record:person})).status,200);assert.equal((await call(admin,{type:'person',record:{...person,id:'person-two-123',document:'102',company:'E-SECURITY'}})).status,200);
const permit={id:'permit-one-123',personId:person.id,kind:'Permiso',start:'2026-10-10T00:00:00-05:00',end:'2026-10-20T00:00:00-05:00',place:'Descanso'};assert.equal(rules.validateRecord('event',permit).extraDays,0);assert.throws(()=>rules.validateRecord('event',{...permit,end:'2026-10-21T00:00:00-05:00'}));assert.equal(rules.validateRecord('event',{...permit,end:'2026-10-21T00:00:00-05:00',authorizedBy:'Jefe autorizado'}).extraDays,1);assert.equal((await call(admin,{type:'event',record:permit})).status,200);assert.equal((await call(admin,{type:'event',record:{...permit,id:'overlap-permit'}})).status,400);
assert.equal((await call(admin,{type:'discipline',record:{id:'sanction-one-123',personId:person.id,kind:'Sanción',reason:'Incumplimiento',start:'2026-10-01',end:'2026-10-03'}})).status,200);
const generated=await call(admin,{type:'invite',personId:person.id});assert.equal(generated.status,200);assert.equal(generated.data.code,undefined);const invitation=generated.data.url.split('#activate=')[1];assert.equal(invitation.length,64);assert.notEqual(sql.prepare('SELECT token_hash FROM employee_invitations').get().token_hash,invitation);assert.equal(Date.parse(generated.data.expiresAt),clock+86400000);assert.equal((await call(self,{action:'activate',document:'102',password:'new-password',invitation},'')).status,400);assert.equal((await call(self,{action:'activate',document:person.document,password:'short',invitation},'')).status,400);const activated=await call(self,{action:'activate',document:person.document,password:'new-password',invitation},'');assert.equal(activated.status,200);assert.equal((await call(self,{action:'activate',document:person.document,password:'other-password',invitation},'')).status,400);assert.equal(sql.prepare('SELECT salt FROM employee_credentials').get().salt.length,36);assert.notEqual(sql.prepare('SELECT code_hash FROM employee_credentials').get().code_hash,'new-password');const login=await call(self,{action:'login',document:person.document,password:'new-password'},'');assert.equal(login.status,200);const token=login.data.token;const own=await call(self,null,token);assert.equal(own.status,200);assert.equal(own.data.person.id,person.id);assert.equal(own.data.discipline,undefined);assert.equal(own.data.person.code_hash,undefined);assert.equal(own.data.date,'2026-10-05');assert.equal((await call(admin,null,token)).status,401);assert.equal((await call(self,null,token+'bad')).status,401);
const meals={action:'meals',date:'2026-10-05',breakfast:true,lunch:false,dinner:true};assert.equal((await call(self,meals,token)).status,200);assert.equal(sql.prepare('SELECT count(*) AS n FROM meals').get().n,1);assert.equal((await call(self,{...meals,lunch:true},token)).status,200);assert.equal(sql.prepare('SELECT count(*) AS n FROM meals').get().n,1);
clock=Date.parse('2026-10-05T00:00:00-05:00');assert.equal((await call(self,meals,token)).status,409);assert.equal((await call(self,null,token)).data.date,'2026-10-06');
const ownPermission=await call(self,{action:'permission',record:{...permit,id:'self-permit-123',personId:'person-two-123',start:'2026-10-06T00:00:00-05:00',end:'2026-10-07T00:00:00-05:00'}},token);assert.equal(ownPermission.status,200);assert.equal(sql.prepare("SELECT person_id FROM events WHERE id='self-permit-123'").get().person_id,person.id);assert.equal((await call(self,{...meals,date:'2026-10-06'},token)).status,409);
const vacation={...permit,id:'vacation-123',kind:'Vacaciones',start:'2026-10-22T00:00:00-05:00',end:'2026-10-25T00:00:00-05:00'};assert.equal(rules.mealBlocked(p,[rules.validateRecord('event',vacation)],'2026-10-24'),true);assert.equal(rules.mealBlocked(p,[rules.validateRecord('event',vacation)],'2026-10-25'),false);
const older=await call(admin,{type:'invite',personId:person.id});assert.equal((await call(self,null,token)).status,200);const newer=await call(admin,{type:'invite',personId:person.id});assert.equal((await call(self,{action:'activate',document:person.document,password:'replacement-password',invitation:older.data.url.split('#activate=')[1]},'')).status,400);const renewed=await call(self,{action:'activate',document:person.document,password:'replacement-password',invitation:newer.data.url.split('#activate=')[1]},'');assert.equal(renewed.status,200);assert.equal((await call(self,null,token)).status,401);assert.equal((await call(self,{action:'login',document:person.document,password:'new-password'},'')).status,401);
const expire=await call(admin,{type:'invite',personId:person.id});clock+=86400000;assert.equal((await call(self,{action:'activate',document:person.document,password:'not-used-password',invitation:expire.data.url.split('#activate=')[1]},'')).status,400);
// Previous generated keys remain usable until their owners choose a password.
await sql.exec("INSERT INTO employee_credentials (person_id,code_hash,version,updated_at) VALUES ('person-two-123','"+await server.hash('legacy-key')+"','old-version','now')");assert.equal((await call(self,{action:'login',document:'102',code:'legacy-key'},'')).status,200);
// Roles are granted only by an authenticated administrator and come from the server-side invitation.
const worker=await call(self,{action:'login',document:'102',code:'legacy-key'},'');assert.equal(worker.data.accessRole,'Laboral');assert.equal((await call(admin,{type:'invite',personId:person.id,accessRole:'Administrador'},worker.data.token)).status,401);
assert.equal((await call(admin,{type:'invite',personId:person.id,accessRole:'Other'})).status,400);
assert.equal((await call(admin,{type:'person',record:{...person,id:'person-admin-123',document:'103'}})).status,200);
const adminInvite=await call(admin,{type:'invite',personId:'person-admin-123',accessRole:'Administrador'});assert.equal(adminInvite.status,200);assert.equal(adminInvite.data.accessRole,'Administrador');const newAdmin=await call(self,{action:'activate',document:'103',password:'admin-person-password',invitation:adminInvite.data.url.split('#activate=')[1],accessRole:'Laboral'},'');assert.equal(newAdmin.status,200);assert.equal(newAdmin.data.accessRole,'Administrador');assert.equal((await call(admin,null,newAdmin.data.token)).status,200);
const anotherInvite=await call(admin,{type:'invite',personId:person.id,accessRole:'Administrador'},newAdmin.data.token);assert.equal(anotherInvite.status,200);const anotherAdmin=await call(self,{action:'activate',document:person.document,password:'second-admin-password',invitation:anotherInvite.data.url.split('#activate=')[1]},'');assert.equal(anotherAdmin.status,200);assert.equal((await call(admin,null,anotherAdmin.data.token)).status,200);assert.equal((await call(admin,null,newAdmin.data.token)).status,200);
const adminAuth=load('app/api/admin-auth/route.ts');assert.equal((await call(adminAuth,{action:'login',username:'103',password:'admin-person-password'},'')).status,200);assert.equal((await call(adminAuth,{action:'login',username:'102',password:'legacy-key'},'')).status,401);
const down=await call(admin,{type:'invite',personId:'person-admin-123',accessRole:'Laboral'});const downgraded=await call(self,{action:'activate',document:'103',password:'laboral-person-password',invitation:down.data.url.split('#activate=')[1],accessRole:'Administrador'},'');assert.equal(downgraded.status,200);assert.equal(downgraded.data.accessRole,'Laboral');assert.equal((await call(admin,null,newAdmin.data.token)).status,401);assert.equal((await call(admin,null,downgraded.data.token)).status,401);
await sql.exec("UPDATE people SET status='Inactivo' WHERE id='person-one-123'");assert.equal((await call(admin,null,anotherAdmin.data.token)).status,401);assert.equal((await call(adminAuth,{action:'login',username:'101',password:'second-admin-password'},'')).status,401);
for(let i=0;i<10;i++)assert.equal((await call(self,{action:'login',document:'102',code:'wrong'},'')).status,401);assert.equal((await call(self,{action:'login',document:'102',code:'wrong'},'')).status,429);
console.log('PASS migrations preserve legacy profiles; closed companies/roles; separate names and lists; 10-day limit and authorizer; overlap checks; sanctions; personal access and isolation; meal edits; midnight cutoff; absence blocks; invitation document validation, 24-hour expiry, single-use activation, replacement and password rotation; legacy access; multiple admins, admin login, labor isolation, forged-role rejection, downgrade and inactive revocation; rate limit');})().catch(e=>{console.error(e);process.exit(1)});
