const fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript'),assert=require('node:assert/strict');const{DatabaseSync}=require('node:sqlite');
let clock=Date.parse('2026-10-04T23:59:59-05:00');class TestDate extends Date{constructor(...a){super(...(a.length?a:[clock]));}static now(){return clock;}}
const sql=new DatabaseSync(':memory:');const migrated=fs.readdirSync('drizzle').filter(x=>x.endsWith('.sql')).sort();for(const file of migrated.slice(0,2))sql.exec(fs.readFileSync('drizzle/'+file,'utf8'));sql.exec("INSERT INTO people (id,document,name,role,status,phone,notes,updated_at,titles,strengths) VALUES ('legacy-person','123','Nombre Antiguo','Escolta','Disponible','','','now','Bachiller','Trabajo en equipo')");for(const file of migrated.slice(2))sql.exec(fs.readFileSync('drizzle/'+file,'utf8'));assert.equal(sql.prepare("SELECT name FROM people WHERE id='legacy-person'").get().name,'Nombre Antiguo');assert.equal(sql.prepare("SELECT titles FROM people WHERE id='legacy-person'").get().titles,'Bachiller');
const DB={prepare(query){let values=[];return{bind(...args){assert.ok(args.length<=100,'D1 allows at most 100 bind parameters');values=args;return this;},async first(){return sql.prepare(query).get(...values)||null},async all(){return{results:sql.prepare(query).all(...values)}},async run(){const r=sql.prepare(query).run(...values);return{meta:{changes:Number(r.changes)}}}}}};
DB.batch=async statements=>{sql.exec('BEGIN');try{const result=[];for(const statement of statements)result.push(await statement.run());sql.exec('COMMIT');return result;}catch(e){sql.exec('ROLLBACK');throw e;}};
const env={DB,GP_ACCESS_HASH:''},cache={};function load(path){if(cache[path])return cache[path];const module={exports:{}};const ctx={module,exports:module.exports,require:id=>{if(id==='./activities'||id==='@/lib/activities')return load('lib/activities.ts');if(id==='cloudflare:workers')return{env};if(id==='@/lib/personnel'||id==='./personnel')return load('lib/personnel.ts');if(id==='./workload'||id==='@/lib/workload')return load('lib/workload.ts');if(id==='./qualifications'||id==='@/lib/qualifications')return load('lib/qualifications.ts');if(id==='@/lib/personnel-server')return load('lib/personnel-server.ts');throw Error(id)},crypto:globalThis.crypto,Date:TestDate,TextEncoder,Uint8Array,Request,Response,URL,btoa,atob,console,Intl};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,ctx);return cache[path]=module.exports;}
const rules=load('lib/personnel.ts'),server=load('lib/personnel-server.ts'),admin=load('app/api/data/route.ts'),self=load('app/api/self/route.ts');
const req=(body,token='admin-secret')=>new Request('https://backend.test/api/data',{method:body?'POST':'GET',headers:{Origin:'https://controlesmineras.github.io',Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
async function call(route,body,token){const response=await route[body?'POST':'GET'](req(body,token));return{status:response.status,data:await response.json()};}
(async()=>{env.GP_ACCESS_HASH=await server.hash('admin-secret');
const person={id:'person-one-123',document:'101',firstName:'Ana',secondName:'María',firstSurname:'Del Río',secondSurname:'López',company:'SK',role:'Directora',status:'Disponible',titles:['Bachiller','Técnica'],strengths:['Trabajo en equipo','Disciplina']};assert.throws(()=>rules.validateRecord('person',person));person.role='Director de seguridad';const p=rules.validateRecord('person',person);assert.equal(p.name,'Ana María Del Río López');assert.equal(p.titles,'Bachiller\nTécnica');assert.throws(()=>rules.validateRecord('person',{...person,company:'Otra'}));assert.equal((await call(admin,{type:'person',record:person})).status,200);assert.equal((await call(admin,{type:'person',record:{...person,id:'person-two-123',document:'102',company:'E-SECURITY'}})).status,200);
const permit={id:'permit-one-123',personId:person.id,kind:'Permiso',start:'2026-10-10T00:00:00-05:00',end:'2026-10-20T00:00:00-05:00',place:'Descanso'};assert.equal(rules.validateRecord('event',permit).extraDays,0);assert.throws(()=>rules.validateRecord('event',{...permit,end:'2026-10-21T00:00:00-05:00'}));assert.equal(rules.validateRecord('event',{...permit,end:'2026-10-21T00:00:00-05:00',authorizedBy:'Jefe autorizado'}).extraDays,1);assert.equal((await call(admin,{type:'event',record:permit})).status,200);assert.equal((await call(admin,{type:'event',record:{...permit,id:'overlap-permit'}})).status,400);
assert.equal((await call(admin,{type:'discipline',record:{id:'sanction-one-123',personId:person.id,kind:'Sanción',reason:'Incumplimiento',start:'2026-10-01',end:'2026-10-03'}})).status,200);
const generated=await call(admin,{type:'invite',personId:person.id});assert.equal(generated.status,200);assert.equal(generated.data.code,undefined);const invitation=generated.data.url.split('#activate=')[1];assert.equal(invitation.length,64);assert.notEqual(sql.prepare('SELECT token_hash FROM employee_invitations').get().token_hash,invitation);assert.equal(Date.parse(generated.data.expiresAt),clock+86400000);assert.equal((await call(self,{action:'activate',document:'102',password:'new-password',invitation},'')).status,400);assert.equal((await call(self,{action:'activate',document:person.document,password:'short',invitation},'')).status,400);const activated=await call(self,{action:'activate',document:person.document,password:'new-password',invitation},'');assert.equal(activated.status,200);assert.equal((await call(self,{action:'activate',document:person.document,password:'other-password',invitation},'')).status,400);assert.equal(sql.prepare('SELECT salt FROM employee_credentials').get().salt.length,36);assert.notEqual(sql.prepare('SELECT code_hash FROM employee_credentials').get().code_hash,'new-password');const login=await call(self,{action:'login',document:person.document,password:'new-password'},'');assert.equal(login.status,200);const token=login.data.token;const own=await call(self,null,token);assert.equal(own.status,200);assert.equal(own.data.person.id,person.id);assert.equal(own.data.discipline,undefined);assert.equal(own.data.person.code_hash,undefined);assert.equal(own.data.date,'2026-10-05');assert.equal((await call(admin,null,token)).status,401);assert.equal((await call(self,null,token+'bad')).status,401);
const meals={action:'meals',date:'2026-10-05',breakfast:true,lunch:false,dinner:true};assert.equal((await call(self,meals,token)).status,200);assert.equal(sql.prepare('SELECT count(*) AS n FROM meals').get().n,1);assert.equal((await call(self,{...meals,lunch:true},token)).status,200);assert.equal(sql.prepare('SELECT count(*) AS n FROM meals').get().n,1);
clock=Date.parse('2026-10-05T00:00:00-05:00');assert.equal((await call(self,meals,token)).status,409);assert.equal((await call(self,null,token)).data.date,'2026-10-06');
const ownPermission=await call(self,{action:'permission',record:{...permit,id:'self-permit-123',personId:'person-two-123',start:'2026-10-06T00:00:00-05:00',end:'2026-10-07T00:00:00-05:00'}},token);assert.equal(ownPermission.status,200);assert.equal(sql.prepare("SELECT person_id FROM events WHERE id='self-permit-123'").get().person_id,person.id);assert.equal((await call(self,{...meals,date:'2026-10-06'},token)).status,409);
const vacation={...permit,id:'vacation-123',kind:'Vacaciones',start:'2026-10-22T00:00:00-05:00',end:'2026-10-25T00:00:00-05:00'};assert.equal(rules.mealBlocked(p,[rules.validateRecord('event',vacation)],'2026-10-24'),true);assert.equal(rules.mealBlocked(p,[rules.validateRecord('event',vacation)],'2026-10-25'),false);
const older=await call(admin,{type:'invite',personId:person.id});assert.equal((await call(self,null,token)).status,200);const newer=await call(admin,{type:'invite',personId:person.id});assert.equal((await call(self,{action:'activate',document:person.document,password:'replacement-password',invitation:older.data.url.split('#activate=')[1]},'')).status,400);const renewed=await call(self,{action:'activate',document:person.document,password:'replacement-password',invitation:newer.data.url.split('#activate=')[1]},'');assert.equal(renewed.status,200);assert.equal((await call(self,null,token)).status,401);assert.equal((await call(self,{action:'login',document:person.document,password:'new-password'},'')).status,401);
const expire=await call(admin,{type:'invite',personId:person.id});clock+=86400000;assert.equal((await call(self,{action:'activate',document:person.document,password:'not-used-password',invitation:expire.data.url.split('#activate=')[1]},'')).status,400);
// Previous generated keys remain usable until their owners choose a password.
await sql.exec("INSERT INTO employee_credentials (person_id,code_hash,version,updated_at) VALUES ('person-two-123','"+await server.hash('legacy-key')+"','old-version','now')");assert.equal((await call(self,{action:'login',document:'102',code:'legacy-key'},'')).status,200);
// Mandatory requirements apply to every worker; qualification and contract dates survive legacy edits.
const qualifications=load('lib/qualifications.ts'),course={id:'mandatory-course-one',name:'Capacitación de prueba',validityMonths:12};
assert.equal((await call(admin,{type:'course',record:course})).status,200);assert.equal((await call(admin,{type:'course',record:{...course,id:'mandatory-course-two'}})).status,409);assert.equal((await call(admin,{type:'course',record:{...course,name:'Capacitación actualizada'}})).status,200);assert.equal((await call(admin,null)).data.trainingRequirements[0].name,'Capacitación actualizada');assert.throws(()=>rules.validateRecord('course',{...course,validityMonths:-1}));
const today=rules.bogotaDate(),cert={id:'certificate-one-123',name:'Capacitación de prueba',requirementId:course.id,issuedOn:today,expiresOn:rules.addDays(today,30),noExpiry:false,category:''},car={...cert,id:'car-license-123',requirementId:'license-car',name:'Licencia carro',expiresOn:rules.addDays(today,-1),issuedOn:'',category:'B1'};
const withCert={...person,qualifications:[cert,car],contractEnd:rules.addDays(today,60),contractIndefinite:false};assert.equal((await call(admin,{type:'person',record:withCert})).status,200);assert.equal((await call(admin,{type:'person',record:person})).status,200);const loaded=(await call(admin,null)).data.people.find(x=>x.id===person.id);assert.equal(JSON.parse(loaded.qualifications).length,2);assert.equal(loaded.contractEnd,withCert.contractEnd);assert.equal(qualifications.requirementStatus(loaded,course,today).status,'Próxima a vencer');assert.equal(qualifications.requirementStatus(loaded,qualifications.LICENSES[0],today).status,'Vencida');assert.equal(qualifications.requirementStatus(loaded,qualifications.LICENSES[1],today).status,'Pendiente');assert.equal(qualifications.expiryStatus(today,false,today),'Próxima a vencer');assert.equal(qualifications.expiryStatus(rules.addDays(today,31),false,today),'Vigente');assert.equal(qualifications.addMonths('2024-02-29',12),'2025-02-28');assert.throws(()=>rules.validateRecord('person',{...withCert,contractEnd:'2026-02-30'}));assert.throws(()=>qualifications.validateQualifications([{...car,noExpiry:true}]));assert.throws(()=>qualifications.validateQualifications('broken-json'));assert.throws(()=>qualifications.validateQualifications([{...cert,expiresOn:'2026-02-30'}]));assert.equal(qualifications.personQualifications({...person,titles:'Bachiller'}).some(q=>q.name==='Bachiller'),true);assert.equal(qualifications.requirements({people:[],events:[],trainingRequirements:[course]}).length,3);
const legacyWorker=await call(self,{action:'login',document:'102',code:'legacy-key'},'');assert.equal((await call(admin,{type:'course',record:{...course,name:'No autorizado'}},legacyWorker.data.token)).status,401);const ownProfile=await call(self,null,legacyWorker.data.token);assert.equal(ownProfile.data.person.id,'person-two-123');assert.equal(ownProfile.data.people,undefined);assert.equal(ownProfile.data.trainingRequirements.length,1);
assert.equal((await call(admin,null)).data.workSettings.minRestHours,8);assert.equal((await call(admin,{type:'settings',record:{id:'workload-settings',minRestHours:6,maxWorkHours24:10}})).status,200);assert.equal((await call(admin,null)).data.workSettings.maxWorkHours24,10);assert.equal((await call(self,null,legacyWorker.data.token)).data.workSettings.minRestHours,6);assert.equal((await call(admin,{type:'settings',record:{id:'workload-settings',minRestHours:1,maxWorkHours24:1}},legacyWorker.data.token)).status,401);assert.equal((await call(admin,{type:'settings',record:{id:'workload-settings',minRestHours:8,maxWorkHours24:12}})).status,200);
// Roles are granted only by an authenticated administrator and come from the server-side invitation.
const worker=await call(self,{action:'login',document:'102',code:'legacy-key'},'');assert.equal(worker.data.accessRole,'Laboral');assert.equal((await call(admin,{type:'invite',personId:person.id,accessRole:'Administrador'},worker.data.token)).status,401);
assert.equal((await call(admin,{type:'invite',personId:person.id,accessRole:'Other'})).status,400);
assert.equal((await call(admin,{type:'person',record:{...person,id:'person-admin-123',document:'103'}})).status,200);
const adminInvite=await call(admin,{type:'invite',personId:'person-admin-123',accessRole:'Administrador'});assert.equal(adminInvite.status,200);assert.equal(adminInvite.data.accessRole,'Administrador');const newAdmin=await call(self,{action:'activate',document:'103',password:'admin-person-password',invitation:adminInvite.data.url.split('#activate=')[1],accessRole:'Laboral'},'');assert.equal(newAdmin.status,200);assert.equal(newAdmin.data.accessRole,'Administrador');assert.equal((await call(admin,null,newAdmin.data.token)).status,200);
// An administrator keeps their own employee portal and reports only their own meals and absences.
assert.equal((await call(self,null,newAdmin.data.token)).data.person.id,'person-admin-123');
const adminDay=rules.addDays(rules.bogotaDate(),1);assert.equal((await call(self,{action:'meals',date:adminDay,breakfast:true,lunch:true,dinner:false},newAdmin.data.token)).status,200);assert.equal(sql.prepare('SELECT person_id FROM meals WHERE person_id=? AND date=?').get('person-admin-123',adminDay).person_id,'person-admin-123');
const ownVacation={id:'admin-own-vacation',personId:'person-two-123',kind:'Servicio',start:'2026-12-01T00:00:00-05:00',end:'2026-12-05T00:00:00-05:00',place:'Vacaciones personales'};assert.equal((await call(self,{action:'vacation',record:ownVacation},newAdmin.data.token)).status,200);const ownRow=sql.prepare('SELECT person_id,kind FROM events WHERE id=?').get(ownVacation.id);assert.equal(ownRow.person_id,'person-admin-123');assert.equal(ownRow.kind,'Vacaciones');
assert.equal((await call(self,{action:'vacation',record:{...ownVacation,id:'permit-one-123'}},newAdmin.data.token)).status,400);assert.equal((await call(admin,null,newAdmin.data.token)).status,200);
const anotherInvite=await call(admin,{type:'invite',personId:person.id,accessRole:'Administrador'},newAdmin.data.token);assert.equal(anotherInvite.status,200);const anotherAdmin=await call(self,{action:'activate',document:person.document,password:'second-admin-password',invitation:anotherInvite.data.url.split('#activate=')[1]},'');assert.equal(anotherAdmin.status,200);assert.equal((await call(admin,null,anotherAdmin.data.token)).status,200);assert.equal((await call(admin,null,newAdmin.data.token)).status,200);
// Audit records use the verified session, are atomic, and survive retries without duplication.
const change={type:'person',operationId:'audit-operation-one',actorName:'Forged administrator',record:{...person,id:'audit-person-one',document:'204',firstName:'Cocina',role:'Preparación de alimentos'}};
assert.equal((await call(admin,change,newAdmin.data.token)).status,200);
const log=sql.prepare('SELECT * FROM audit_logs WHERE operation_id=?').get(change.operationId);assert.equal(log.actor_id,'person-admin-123');assert.equal(log.actor_name,'Ana María Del Río López');assert.ok(!log.changes.includes('Forged administrator'));
assert.equal((await call(admin,change,newAdmin.data.token)).status,200);assert.equal(sql.prepare('SELECT count(*) AS n FROM audit_logs WHERE operation_id=?').get(change.operationId).n,1);
const auditCount=sql.prepare('SELECT count(*) AS n FROM audit_logs').get().n;assert.equal((await call(admin,{type:'event',record:{...permit,id:'audit-overlap-one'}},newAdmin.data.token)).status,400);assert.equal(sql.prepare('SELECT count(*) AS n FROM audit_logs').get().n,auditCount);
assert.equal((await call(admin,{type:'discipline',record:{id:'sanction-one-123',personId:'person-two-123',kind:'Sanción',reason:'Cambio',start:'2026-10-01',end:'2026-10-03'}},newAdmin.data.token)).status,400);
const originalBatch=DB.batch;DB.batch=async statements=>{sql.exec('BEGIN');try{await statements[0].run();throw Error('Audit unavailable');}catch(e){sql.exec('ROLLBACK');throw e;}};
assert.equal((await call(admin,{...change,operationId:'audit-failure-one',record:{...change.record,firstName:'No guardar'}})).status,400);assert.equal(sql.prepare("SELECT first_name FROM people WHERE id='audit-person-one'").get().first_name,'Cocina');DB.batch=originalBatch;
// Food preparation users see only diner names and food selections, not personnel records.
const cookInvite=await call(admin,{type:'invite',personId:'audit-person-one'});const cook=await call(self,{action:'activate',document:'204',password:'cook-password',invitation:cookInvite.data.url.split('#activate=')[1]},'');assert.equal(cook.status,200);
const kitchen=load('app/api/kitchen/route.ts');assert.equal((await call(kitchen,null,worker.data.token)).status,401);assert.equal((await call(kitchen,null,cook.data.token)).status,200);assert.equal((await call(admin,null,cook.data.token)).status,401);
const prepDate=(await call(kitchen,null,cook.data.token)).data.date;sql.prepare('INSERT INTO meals (id,person_id,date,breakfast,lunch,dinner,updated_at) VALUES (?,?,?,?,?,?,?)').run('cook-test-meal','person-two-123',prepDate,1,0,1,'now');
const prep=(await call(kitchen,null,cook.data.token)).data;assert.equal(prep.rows.filter(p=>p.id==='person-two-123').length,1);assert.equal(prep.rows.find(p=>p.id==='person-two-123').name,'Ana María Del Río López');assert.equal(prep.rows[0].document,undefined);assert.equal(prep.rows[0].notes,undefined);assert.equal(prep.rows[0].company,undefined);const cookSelf=(await call(self,null,cook.data.token)).data;assert.equal(cookSelf.events,undefined);assert.equal(cookSelf.person.document,undefined);assert.equal((await call(self,{action:'permission',record:ownVacation},cook.data.token)).status,403);
sql.prepare("UPDATE people SET status='Permiso extraordinario por calamidad' WHERE id='person-two-123'").run();assert.equal((await call(kitchen,null,cook.data.token)).data.rows.some(p=>p.id==='person-two-123'),false);assert.equal(rules.mealBlocked({...p,status:'Permiso extraordinario por calamidad'},[],prepDate),true);sql.prepare("UPDATE people SET status='Disponible' WHERE id='person-two-123'").run();
// Deliveries are persisted per employee, date and meal, with the authenticated cook's identity.
const deliveryDate=rules.bogotaDate();sql.prepare('INSERT INTO meals (id,person_id,date,breakfast,lunch,dinner,updated_at) VALUES (?,?,?,?,?,?,?)').run('today-test-meal','person-two-123',deliveryDate,1,0,1,'now');
const delivery={action:'attendance',date:deliveryDate,personId:'person-two-123',meal:'breakfast',received:true,updatedBy:'forged-admin'};
assert.equal((await call(kitchen,delivery,worker.data.token)).status,401);assert.equal((await call(kitchen,{...delivery,received:'yes'},cook.data.token)).status,400);assert.equal((await call(kitchen,{...delivery,date:rules.addDays(deliveryDate,1)},cook.data.token)).status,409);assert.equal((await call(kitchen,{...delivery,meal:'lunch'},cook.data.token)).status,409);assert.equal((await call(kitchen,{...delivery,personId:'does-not-exist'},cook.data.token)).status,409);
assert.equal((await call(kitchen,delivery,cook.data.token)).status,200);assert.equal((await call(kitchen,delivery,cook.data.token)).status,200);const receipt=sql.prepare('SELECT * FROM meal_attendance').get();assert.equal(receipt.updated_by,'audit-person-one');assert.equal(receipt.received,1);assert.equal(sql.prepare('SELECT count(*) AS n FROM meal_attendance').get().n,1);
await call(admin,{type:'person',record:{...change.record,id:'cook-two-person',document:'205'}});const secondCookLink=await call(admin,{type:'invite',personId:'cook-two-person'});const secondCook=await call(self,{action:'activate',document:'205',password:'second-cook-password',invitation:secondCookLink.data.url.split('#activate=')[1]},'');assert.equal(secondCook.status,200);
const todayQuery=new Request('https://backend.test/api/kitchen?date='+deliveryDate,{headers:{Authorization:'Bearer '+secondCook.data.token}});const shared=await (await kitchen.GET(todayQuery)).json();assert.equal(shared.attendance[0].received,1);assert.equal(shared.rows.find(p=>p.id==='person-two-123').breakfast,1);
assert.equal((await call(kitchen,{...delivery,received:false},secondCook.data.token)).status,200);assert.equal(sql.prepare('SELECT received,updated_by FROM meal_attendance').get().received,0);assert.equal(sql.prepare('SELECT updated_by FROM meal_attendance').get().updated_by,'cook-two-person');assert.equal((await call(kitchen,{...delivery,meal:'dinner'},secondCook.data.token)).status,200);assert.equal(sql.prepare('SELECT count(*) AS n FROM meal_attendance').get().n,2);assert.equal(sql.prepare("SELECT received FROM meal_attendance WHERE meal='breakfast'").get().received,0);
sql.prepare("UPDATE people SET status='Permiso extraordinario por calamidad' WHERE id='person-two-123'").run();assert.equal((await call(kitchen,delivery,cook.data.token)).status,409);sql.prepare("UPDATE people SET status='Disponible' WHERE id='person-two-123'").run();
const adminAuth=load('app/api/admin-auth/route.ts');assert.equal((await call(adminAuth,{action:'login',username:'103',password:'admin-person-password'},'')).status,200);assert.equal((await call(adminAuth,{action:'login',username:'102',password:'legacy-key'},'')).status,401);
// One group activity is atomically assigned to each participant and shown in their own portal.
const helper=load('lib/activities.ts'),activity={id:'scheduled-activity-one',name:'Ronda y verificación de accesos',start:'2026-12-10T08:00:00-05:00',end:'2026-12-10T11:00:00-05:00',coordinatorId:'person-admin-123',participants:[{personId:'person-admin-123',function:'Coordinar'},{personId:'person-two-123',function:'Verificar accesos'}]};
assert.throws(()=>helper.validateActivity({...activity,coordinatorId:'not-selected'}));assert.throws(()=>helper.validateActivity({...activity,participants:[activity.participants[0],activity.participants[0]]}));assert.equal((await call(admin,{type:'activity',record:activity},worker.data.token)).status,401);
const actOp={type:'activity',record:activity,operationId:'activity-operation-one'};assert.equal((await call(admin,actOp,newAdmin.data.token)).status,200);assert.equal(sql.prepare('SELECT count(*) AS n FROM activities WHERE id=?').get(activity.id).n,1);assert.equal(sql.prepare('SELECT count(*) AS n FROM activity_participants WHERE activity_id=?').get(activity.id).n,2);assert.equal(sql.prepare('SELECT count(*) AS n FROM events WHERE activity_id=?').get(activity.id).n,2);
assert.equal((await call(admin,actOp,newAdmin.data.token)).status,200);assert.equal(sql.prepare('SELECT count(*) AS n FROM events WHERE activity_id=?').get(activity.id).n,2);assert.equal(sql.prepare('SELECT count(*) AS n FROM audit_logs WHERE operation_id=?').get(actOp.operationId).n,1);assert.equal(sql.prepare('SELECT actor_id FROM audit_logs WHERE operation_id=?').get(actOp.operationId).actor_id,'person-admin-123');
const ownActivity=(await call(self,null,worker.data.token)).data.activities.find(a=>a.id===activity.id);assert.equal(ownActivity.participants.length,1);assert.equal(ownActivity.participants[0].personId,'person-two-123');assert.equal(ownActivity.participants[0].function,'Verificar accesos');assert.equal(ownActivity.coordinatorName,'Ana María Del Río López');assert.equal(ownActivity.participants[0].document,undefined);assert.equal((await call(self,null,cook.data.token)).data.activities,undefined);
const snapshotActivities=(await call(admin,null)).data,stored=snapshotActivities.activities.find(a=>a.id===activity.id),copy=helper.activityMessage(stored,snapshotActivities.people);assert.ok(copy.includes('Fecha desde: 10/12/2026'));assert.ok(copy.includes('Fecha hasta: 10/12/2026'));assert.ok(copy.includes('Horario desde: 08:00'));assert.ok(copy.includes('Horario hasta: 11:00'));assert.ok(copy.includes('Encargado: Ana María Del Río López'));assert.ok(copy.includes('Verificar accesos'));
assert.equal((await call(admin,{type:'event',record:{id:'overlapping-group-event',personId:'person-two-123',kind:'Servicio',start:activity.start,end:activity.end,place:'Cruce'}})).status,400);const child=sql.prepare('SELECT id FROM events WHERE activity_id=? LIMIT 1').get(activity.id);assert.equal((await call(admin,{type:'event',record:{id:child.id,personId:'person-admin-123',kind:'Servicio',start:'2026-12-10T12:00:00-05:00',end:'2026-12-10T13:00:00-05:00',place:'Edición individual'}})).status,400);
const update={...activity,name:'Ronda actualizada',end:'2026-12-10T12:00:00-05:00',participants:[activity.participants[0]]};assert.equal((await call(admin,{type:'activity',record:update,operationId:'activity-operation-two'})).status,200);assert.equal(sql.prepare('SELECT count(*) AS n FROM activities').get().n,1);assert.equal(sql.prepare('SELECT count(*) AS n FROM events WHERE activity_id=?').get(activity.id).n,1);assert.equal((await call(self,null,worker.data.token)).data.activities.some(a=>a.id===activity.id),false);
const existingRevision=sql.prepare('SELECT revision FROM activities WHERE id=?').get(activity.id).revision;const normalBatch=DB.batch;DB.batch=async statements=>{sql.exec('BEGIN');try{for(let i=0;i<Math.min(3,statements.length);i++)await statements[i].run();throw Error('Simulated failure');}catch(e){sql.exec('ROLLBACK');throw e;}};assert.equal((await call(admin,{type:'activity',record:{...update,name:'No guardar'},operationId:'activity-operation-failure'})).status,400);DB.batch=normalBatch;assert.equal(sql.prepare('SELECT revision FROM activities WHERE id=?').get(activity.id).revision,existingRevision);assert.equal(sql.prepare('SELECT count(*) AS n FROM events WHERE activity_id=?').get(activity.id).n,1);
// A conflicting assignment arriving after validation leaves the existing activity and roster untouched.
DB.batch=async statements=>{sql.prepare("INSERT INTO events (id,person_id,kind,start,end,place,notes,updated_at) VALUES ('concurrent-activity-conflict','person-two-123','Servicio','2026-12-10T13:00:00.000Z','2026-12-10T16:00:00.000Z','Concurrente','','now')").run();return normalBatch(statements);};assert.equal((await call(admin,{type:'activity',record:activity,operationId:'activity-operation-race'})).status,400);DB.batch=normalBatch;assert.equal(sql.prepare('SELECT revision FROM activities WHERE id=?').get(activity.id).revision,existingRevision);assert.equal(sql.prepare('SELECT count(*) AS n FROM activity_participants WHERE activity_id=?').get(activity.id).n,1);sql.prepare("DELETE FROM events WHERE id='concurrent-activity-conflict'").run();
// Chunked D1 statements stay within 100 bind values when selecting the full security team.
const realBatch=DB.batch;DB.batch=async statements=>realBatch(statements);const many=[];for(let i=0;i<31;i++){const id='bulk-worker-'+String(i).padStart(3,'0');sql.prepare("INSERT INTO people (id,document,name,role,status,updated_at) VALUES (?,?,?,?,?,?)").run(id,'bulk-doc-'+i,'Funcionario '+i,'Operador de seguridad','Disponible','now');many.push({personId:id,function:''});}const full={...activity,id:'full-team-activity',start:'2026-12-15T08:00:00-05:00',end:'2026-12-15T10:00:00-05:00',coordinatorId:many[0].personId,participants:many};assert.equal((await call(admin,{type:'activity',record:full})).status,200);assert.equal(sql.prepare('SELECT count(*) AS n FROM events WHERE activity_id=?').get(full.id).n,31);DB.batch=realBatch;
console.log('PASS group activities: single parent, assignments, own portal isolation, message fields, atomic edits, audit identity, retries, overlap race and full-team batching');
const down=await call(admin,{type:'invite',personId:'person-admin-123',accessRole:'Laboral'});const downgraded=await call(self,{action:'activate',document:'103',password:'laboral-person-password',invitation:down.data.url.split('#activate=')[1],accessRole:'Administrador'},'');assert.equal(downgraded.status,200);assert.equal(downgraded.data.accessRole,'Laboral');assert.equal((await call(admin,null,newAdmin.data.token)).status,401);assert.equal((await call(admin,null,downgraded.data.token)).status,401);
await sql.exec("UPDATE people SET status='Inactivo' WHERE id='person-one-123'");assert.equal((await call(admin,null,anotherAdmin.data.token)).status,401);assert.equal((await call(adminAuth,{action:'login',username:'101',password:'second-admin-password'},'')).status,401);
for(let i=0;i<10;i++)assert.equal((await call(self,{action:'login',document:'102',code:'wrong'},'')).status,401);assert.equal((await call(self,{action:'login',document:'102',code:'wrong'},'')).status,429);
console.log('PASS migrations preserve legacy profiles; closed companies/roles; separate names and lists; 10-day limit and authorizer; overlap checks; sanctions; personal access and isolation; meal edits; midnight cutoff; absence blocks; invitation document validation, 24-hour expiry, single-use activation, replacement and password rotation; legacy access; multiple admins, admin login, labor isolation, forged-role rejection, downgrade and inactive revocation; rate limit');})().catch(e=>{console.error(e);process.exit(1)});
