import { sqliteTable, text, integer, real, index, uniqueIndex } from 'drizzle-orm/sqlite-core';
export const people=sqliteTable('people',{id:text('id').primaryKey(),document:text('document').notNull().unique(),name:text('name').notNull(),company:text('company').notNull().default(''),firstName:text('first_name').notNull().default(''),secondName:text('second_name').notNull().default(''),firstSurname:text('first_surname').notNull().default(''),secondSurname:text('second_surname').notNull().default(''),role:text('role').notNull(),phone:text('phone').notNull().default(''),status:text('status').notNull().default('Disponible'),notes:text('notes').notNull().default(''),titles:text('titles').notNull().default(''),strengths:text('strengths').notNull().default(''),qualifications:text('qualifications_json').notNull().default('[]'),contractEnd:text('contract_end').notNull().default(''),contractIndefinite:integer('contract_indefinite').notNull().default(0),updatedAt:text('updated_at').notNull()});
export const events=sqliteTable('events',{id:text('id').primaryKey(),personId:text('person_id').notNull().references(()=>people.id),kind:text('kind').notNull(),start:text('start').notNull(),end:text('end').notNull(),place:text('place').notNull().default(''),notes:text('notes').notNull().default(''),authorizedBy:text('authorized_by').notNull().default(''),extraDays:integer('extra_days').notNull().default(0),updatedAt:text('updated_at').notNull()},t=>[index('idx_events_person_start').on(t.personId,t.start)]);
export const discipline=sqliteTable('discipline',{id:text('id').primaryKey(),personId:text('person_id').notNull().references(()=>people.id),kind:text('kind').notNull(),reason:text('reason').notNull(),start:text('start').notNull(),end:text('end').notNull(),notes:text('notes').notNull().default(''),updatedAt:text('updated_at').notNull()});
export const meals=sqliteTable('meals',{id:text('id').primaryKey(),personId:text('person_id').notNull().references(()=>people.id),date:text('date').notNull(),breakfast:integer('breakfast').notNull().default(0),lunch:integer('lunch').notNull().default(0),dinner:integer('dinner').notNull().default(0),updatedAt:text('updated_at').notNull()},t=>[uniqueIndex('idx_meal_person_date').on(t.personId,t.date)]);
export const credentials=sqliteTable('employee_credentials',{personId:text('person_id').primaryKey().references(()=>people.id),codeHash:text('code_hash').notNull(),salt:text('salt').notNull().default(''),accessRole:text('access_role').notNull().default('Laboral'),version:text('version').notNull(),updatedAt:text('updated_at').notNull()});
export const invitations=sqliteTable('employee_invitations',{personId:text('person_id').primaryKey().references(()=>people.id),tokenHash:text('token_hash').notNull().unique(),expiresAt:integer('expires_at').notNull(),usedClaim:text('used_claim'),accessRole:text('access_role').notNull().default('Laboral'),createdAt:text('created_at').notNull()});
export const attempts=sqliteTable('login_attempts',{key:text('key').primaryKey(),count:integer('count').notNull(),resetAt:integer('reset_at').notNull()});

export const adminCredentials=sqliteTable('admin_credentials',{username:text('username').primaryKey(),passwordHash:text('password_hash').notNull(),salt:text('salt').notNull(),version:text('version').notNull(),createdAt:text('created_at').notNull()});

export const trainingRequirements=sqliteTable('training_requirements',{id:text('id').primaryKey(),name:text('name').notNull().unique(),validityMonths:integer('validity_months').notNull().default(12),updatedAt:text('updated_at').notNull()});

export const workSettings=sqliteTable('work_settings',{id:text('id').primaryKey(),minRestHours:real('min_rest_hours').notNull().default(8),maxWorkHours24:real('max_work_hours_24').notNull().default(12),updatedAt:text('updated_at').notNull()});

export const auditLogs=sqliteTable('audit_logs',{id:text('id').primaryKey(),operationId:text('operation_id').notNull().unique(),occurredAt:text('occurred_at').notNull(),actorId:text('actor_id').notNull(),actorName:text('actor_name').notNull(),actorDocument:text('actor_document').notNull().default(''),entityType:text('entity_type').notNull(),targetId:text('target_id').notNull(),personId:text('person_id').notNull().default(''),action:text('action').notNull(),changes:text('changes').notNull()},t=>[index('idx_audit_time').on(t.occurredAt)]);
