import{bogotaDate,addDays,mealBlocked,type Person,type PersonnelEvent}from'@/lib/personnel';
import{db,hash,passwordHash,same,response,cors,originAllowed,employee,sessionToken,eventColumns,saveEvent,getWorkSettings}from'@/lib/personnel-server';
export async function OPTIONS(){return new Response(null,{status:204,headers:cors})}
export async function GET(req:Request){try{const p=await employee(req);if(!p)return response({error:'Ingresa con tu documento y contraseña.'},401);const date=addDays(bogotaDate(),1);const ev=await db().prepare('SELECT '+eventColumns+' FROM events WHERE person_id=? ORDER BY start DESC').bind(p.id).all<PersonnelEvent>();const meal=await db().prepare('SELECT date,breakfast,lunch,dinner FROM meals WHERE person_id=? AND date=?').bind(p.id,date).first();const trainingRequirements=await db().prepare('SELECT id,name,validity_months AS validityMonths FROM training_requirements ORDER BY name').all();return response({person:p,events:ev.results,trainingRequirements:trainingRequirements.results,workSettings:await getWorkSettings(),date,meal,blocked:mealBlocked(p as Person,ev.results,date)});}catch{return response({error:'No se pudo cargar tu información.'},503)}}
export async function POST(req:Request){try{if(!originAllowed(req))return response({error:'Acceso no autorizado.'},401);const input:any=await req.json();if(input.action==='login'||input.action==='activate'){
 const document=String(input.document||'').trim().slice(0,40),password=String(input.password??input.code??''),key=await hash((req.headers.get('cf-connecting-ip')||'anonymous')+'|'+document),now=Date.now();const attempt=await db().prepare('INSERT INTO login_attempts (key,count,reset_at) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN reset_at<? THEN 1 ELSE count+1 END,reset_at=CASE WHEN reset_at<? THEN excluded.reset_at ELSE reset_at END RETURNING count').bind(key,now+900000,now,now).first<any>();if(attempt?.count>10)return response({error:'Demasiados intentos. Espera 15 minutos.'},429);
 if(input.action==='activate'){
  const token=String(input.invitation||'');if(password.length<8||password.length>128)return response({error:'Elige una contraseña de 8 a 128 caracteres.'},400);if(!/^[a-f0-9]{64}$/.test(token))return response({error:'El enlace no es válido. Solicita uno nuevo al administrador.'},400);const digest=await hash(token),row=await db().prepare('SELECT i.person_id,i.access_role FROM employee_invitations i JOIN people p ON p.id=i.person_id WHERE i.token_hash=? AND i.used_claim IS NULL AND i.expires_at>? AND p.document=? AND p.status<>?').bind(digest,now,document,'Inactivo').first<any>();if(!row)return response({error:'El documento no corresponde o el enlace venció, fue usado o fue reemplazado.'},400);
  const salt=crypto.randomUUID(),version=crypto.randomUUID(),claim=crypto.randomUUID(),codeHash=await passwordHash(password,salt),stamp=new Date().toISOString();const result=await db().batch([
   db().prepare("UPDATE employee_invitations SET used_claim=? WHERE token_hash=? AND used_claim IS NULL AND expires_at>? AND person_id IN (SELECT id FROM people WHERE document=? AND status<>?)").bind(claim,digest,Date.now(),document,'Inactivo'),
   db().prepare('INSERT INTO employee_credentials (person_id,code_hash,salt,version,updated_at,access_role) SELECT person_id,?,?,?,?,access_role FROM employee_invitations WHERE token_hash=? AND used_claim=? ON CONFLICT(person_id) DO UPDATE SET code_hash=excluded.code_hash,salt=excluded.salt,version=excluded.version,updated_at=excluded.updated_at,access_role=excluded.access_role').bind(codeHash,salt,version,stamp,digest,claim)
  ]);if(!result[0].meta.changes||!result[1].meta.changes)return response({error:'El enlace venció, fue usado o fue reemplazado. Solicita uno nuevo.'},409);await db().prepare('DELETE FROM login_attempts WHERE key=?').bind(key).run();return response({token:await sessionToken(row.person_id,version),accessRole:row.access_role});
 }
 const row=await db().prepare('SELECT p.id,c.code_hash,c.salt,c.version,c.access_role FROM people p JOIN employee_credentials c ON c.person_id=p.id WHERE p.document=? AND p.status<>?').bind(document,'Inactivo').first<any>();if(!row||password.length>128||!same(row.salt?await passwordHash(password,row.salt):await hash(password.trim()),row.code_hash))return response({error:'Documento o contraseña incorrectos.'},401);await db().prepare('DELETE FROM login_attempts WHERE key=?').bind(key).run();return response({token:await sessionToken(row.id,row.version),accessRole:row.access_role});
}
const p=await employee(req);if(!p)return response({error:'Tu sesión venció. Ingresa de nuevo.'},401);if(input.action==='permission'){const record=await saveEvent({...input.record,personId:p.id,kind:'Permiso'},p.id);return response({ok:true,id:record.id});}
if(input.action!=='meals')return response({error:'Acción inválida.'},400);const date=addDays(bogotaDate(),1);if(input.date!==date)return response({error:'El plazo para esa fecha cerró a medianoche. Reporta los alimentos del siguiente día.'},409);const events=await db().prepare('SELECT '+eventColumns+' FROM events WHERE person_id=?').bind(p.id).all<PersonnelEvent>();if(mealBlocked(p as Person,events.results,date))return response({error:'No puedes consumir alimentos durante permisos o vacaciones.'},409);for(const k of ['breakfast','lunch','dinner'])if(typeof input[k]!=='boolean')return response({error:'Selección de alimentos inválida.'},400);const start=date+'T05:00:00.000Z',end=addDays(date,1)+'T05:00:00.000Z';const result=await db().prepare(`INSERT INTO meals (id,person_id,date,breakfast,lunch,dinner,updated_at) SELECT ?,?,?,?,?,?,? WHERE EXISTS (SELECT 1 FROM people WHERE id=? AND status NOT IN ('Inactivo','De permiso','De vacaciones')) AND NOT EXISTS (SELECT 1 FROM events WHERE person_id=? AND kind IN ('Permiso','Vacaciones') AND start<? AND end>?) ON CONFLICT(person_id,date) DO UPDATE SET breakfast=excluded.breakfast,lunch=excluded.lunch,dinner=excluded.dinner,updated_at=excluded.updated_at`).bind(crypto.randomUUID(),p.id,date,Number(input.breakfast),Number(input.lunch),Number(input.dinner),new Date().toISOString(),p.id,p.id,end,start).run();if(!result.meta.changes)return response({error:'Los alimentos están bloqueados por permiso o vacaciones.'},409);return response({ok:true,date});}catch(e){return response({error:e instanceof Error?e.message:'No se pudo guardar.'},400)}}
